### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by AlexCuse** [DanWahlin/AngularOverlay#4]
Do you have any interest in publishing this package through Bower?  (or is it there and I can't find it?)

I have no idea how publication works but would be willing to help with the legwork if needed.

**Comment by DanWahlin** [comment]
Hi @AlexCuse. I'm not planning to do much more with it at this point (do plan to convert my original version to Angular 2 though). Just not enough hours in the day. :-)

**Comment by AlexCuse** [comment]
Looks like it's a matter of including a json file in the root directory and
adding a semver tag.

Would you accept a PR with the setup work?  I could also fork your repo and
manage the package for you that way.  This has become an important part of
our angular toolkit, and being able to install it more easily would be
worth the effort on my part.

**Comment by DanWahlin** [comment]
Yeah - it's pretty easy to do. The challenge isn't from the technical side as far as time since it's pretty easy as you mention. By putting stuff on Bower, NPM, etc. it causes additional maintenance work though which I just don't have time for right now unfortunately. You're welcome to manage the package in Bower if you'd like - all I'd ask is that you point back to the original project.

**Comment by AlexCuse** [comment]
Great thanks, I'll get on it this sometime soon.  Sounds like its pretty stable so I'll start with a v1.0 tag.

The fork we have exposes an 'overlayDisplayService' that can be used to disable user input during compute-heavy operations that don't necessarily require HTTP requests.  I will send a PR for that.

**Comment by DanWahlin** [comment]
Sounds good.
